### ISSUE TITLE
Mocha flag -g (--grep) do not work

### ISSUE THREAD

**Issue by qatechniker** [mocha-parallel/mocha-parallel-tests#183]
Hello,

My string to run tests looks like:
`./node_modules/.bin/mocha-parallel-tests --max-parallel 10 --reporter mocha-multi-reporters --reporter-options configFile=./pathToFile/reporter-config.json --timeout 1000000 -g 'SmokeSuite' --recursive ./dist-rest-api-test/pathToTests/`

Flag -g 'SmokeSuite' mean start all the tests which have in title SmokeSuite. It does work with mocha, unfortunately do not work with mocha-parallel-tests

Can you help, please?

**Comment by 1999** [comment]
Hey @qatechniker, thanks for posting this issue and sorry for late response. This looks like a pretty easy thing to fix, we just need to add a handler for `--grep` option: https://github.com/mocha-parallel/mocha-parallel-tests/wiki/Limitations#not-all-mocha-cli-options-are-supported

I'm a bit busy these days so I'll probably fix that in 3-4 days, but you can also send a PR. The idea is to have a handler for this option: https://github.com/mocha-parallel/mocha-parallel-tests/tree/master/src/bin/options.

**Comment by qatechniker** [comment]
Hello @1999 ,

Thanks for pointing me on proper place. I have added needed option.
Unfortunately test fail. 
Not sure What I am doing wrong.
Can you please take a look on PR - https://github.com/mocha-parallel/mocha-parallel-tests/pull/186

Thanks

**Comment by qatechniker** [comment]
@1999 thanks for you help and mocha-parallel, it saved my project and made things easier!
