### ISSUE TITLE
Node v4 compatibility

### ISSUE THREAD

**Issue by pdulapalli** [mocha-parallel/mocha-parallel-tests#190]
Hello,

I was looking for a version of your package that was compatible with Node version 4.

I noticed that the [following build had passed](https://travis-ci.org/mocha-parallel/mocha-parallel-tests/builds/360717303) for Node version 4. 

Which version of your package does this correspond to?

**Comment by 1999** [comment]
Hey @pdulapalli 
That was a 1.x version of `mocha-parallel-tests` which is strictly speaking completely a different package. In v2 we also made a decision to support at least an LTS node version which is now 8. One of the main reasons was the performance - node@8 is much more performant compared to node@6. Also an important point is that node@8 natively supports optimized async/await and we don't need to transpile that to some promises/generators stuff.

Why are you still using such an old node version?

**Comment by 1999** [comment]
Closing because of the inactivity for 2 weeks.
