### ISSUE TITLE
`--retries` CLI issue: Unhandled asynchronous exception: AssertionError [ERR_ASSERTION]: Couldn't find test by id while using retries option

### ISSUE THREAD

**Issue by jetlv** [mocha-parallel/mocha-parallel-tests#194]
Hello. Following are my test code. wrong_case.js

```
describe(`Throwing error`, async function() {    
    before(function () {
    });
    after(function () {
    })
    afterEach(async function () {
    })
    it('Error', async () => {
        console.log(`Ready to throw error`)
        expect(0).equal(1)
    })
})

```
Then I would use following command to trigger the test running - 

`mocha-parallel-tests wrong_case.js --retries 2 --timeout 800000 --max-parallel 5 --recursive`

Error output - 

```
Unhandled asynchronous exception: AssertionError [ERR_ASSERTION]: Couldn't find test by id: 86828835e616131916df2059499fa9d2
    at RunnerMain.emitSubprocessEvents (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/runner.js:138:25)
    at RunnerMain.reEmitSubprocessEvents (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/runner.js:39:14)
    at TaskManager.taskManager.on (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/mocha.js:76:20)
    at emitOne (events.js:116:13)
    at TaskManager.emit (events.js:211:7)
    at TaskManager.onTaskProcessingFinished (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/task-manager.js:19:18)
    at emitTwo (events.js:126:13)
    at TaskManager.emit (events.js:214:7)
    at TaskManager.startTaskProcessing (/root/.nvm/versions/node/v8.9.3/lib/node_modules/mocha-parallel-tests/dist/main/task-manager.js:44:14)
    at <anonymous>

```

**Comment by jetlv** [comment]
Can anybody help on this issue? I guess my code is very clear.

**Comment by 1999** [comment]
Sorry for the long wait. Unfortunately, I'm the only active maintainer for the project at the moment. It looks like the issue is related to the `--retries` option. If you do not use it, everything works fine. Do you actually need it in your tests? @jetlv

**Comment by 1999** [comment]
https://github.com/mocha-parallel/mocha-parallel-tests/pull/196

**Comment by jetlv** [comment]
Hello,

Yes I am running large amount of web e2e tests, so for avoiding some useless bug report, like what were caused by internet connection or some unexpected behavior from browser, I must set retries > 0, which means If all ${retires_count} tests failed, then it is really failing. Is that hard to fix?

Best

**Comment by 1999** [comment]
@jetlv thanks again for finding time to post this issue. Version 2.0.5 is just published and it should contain the fix for your issue.

**Comment by jetlv** [comment]
I really appreciate it! Thanks a lot @1999  It works like a charm now and I believe the module becomes better.

When I use the module in production env, I had found another issue. If possible can you please also look into this.

Here is the sample code, you may run it directly to reproduce the bug in several seconds.

```
let expect = require('chai').expect;


describe(`Demo describe`, async function () {


    let args = [
        {
            name: 'test1'
        },
        {
            name: 'test2'
        }
    ]

    args.forEach(function (arg, index, array) {
        it(arg.name, async function () {
            console.log(`Start running ${arg.name}`)
            expect(0).eq(1)       
        })
    })
})


```
The CLI running command would be 

`mocha-parallel-tests paralleltests.js --retries 2`

This is a common usage of mocha. See [here](https://mochajs.org/#dynamically-generating-tests)  
So if you can fix this issue I guess it would be more reliable. If I need to trigger another issue please let me know.

Thanks

**Comment by jetlv** [comment]
hello @1999  when you have time can you please look into the issue?

thanks so much

**Comment by 1999** [comment]
Hm, that looks really weird. I will take a look at this issue tomorrow.

**Comment by 1999** [comment]
I published a new mocha-parallel-tests version a bit early, so this time it will be a pre-patch version instead. @jetlv could you please take a look at `mocha-parallel-tests@2.0.6-0` and see if it works for you?

**Comment by jetlv** [comment]
Hi @1999  It does work well. Thanks for fixing this issue.

**Comment by 1999** [comment]
No worries!
