### ISSUE TITLE
Why does it works more slower with mocha-parallel-tests?

### ISSUE THREAD

**Issue by yuri-sakharov** [mocha-parallel/mocha-parallel-tests#197]
Hello, 
I tried to use mocha-parallel-tests and expect that it will more faster but something wrong because got results more sower than mocha.

"test-silent": "mocha-parallel-tests -R  min './app/**/*-spec.{js,ts,tsx}'",
npm run test-silent  2388.19s user 225.64s system 352% cpu 12:21.89 total

"test-silent": "mocha -R min './app/**/*-spec.{js,ts,tsx}'",
npm run test-silent  50.07s user 1.81s system 112% cpu 46.087 total

What is wrong?

**Comment by 1999** [comment]
It all depends on what kind of tests you actually have. Also, keep in mind that `mocha` runs all tests inside one process whereas `mocha-parallel-test` runs each of the test files in a separate forked process with an IPC channel (a channel to communicate with the main process). This can improve your workflow for some cases (asynchronously running tasks which require network, for instance, webdriver tasks) but in others, it can make things much slower.

What kind of tests do you have?

**Comment by yuri-sakharov** [comment]
We have ~ 600 test files (~ 6000 tests) for React project. It's unit tests mix. Part of the test are react component test, ajax request tests, tests for functions...

**Comment by 1999** [comment]
I'm almost sure most of these tests are don't require network and are not flaky, right? In this case, there's not much parallelizing would give you. We're currently investigating re-using forked processes (#155) which will make `mocha-parallel-tests` behaviour similar to `jest`. This may increase the speed of tests.

**Comment by yuri-sakharov** [comment]
yes you are right most of the test are not require network. Thanks
