### ISSUE TITLE
grep option broken

### ISSUE THREAD

**Issue by createthis** [mocha-parallel/mocha-parallel-tests#203]
When I run `npm test -- -g 'SomeTest'` with regular `mocha` it will run just the tests within the `SomeTest` describe. However, when I do the same using `mocha-parallel-tests` it runs my entire test suite.

I see there is a `grep` option here: https://github.com/mocha-parallel/mocha-parallel-tests/blob/master/src/bin/options/grep.ts so I'm a little confused. Is it just broken?

```
"mocha-parallel-tests": "^2.0.6-0",
"mocha": "^5.2.0",
```

```bash
$ node -v
v8.12.0
$ npm -v
6.4.1
```

**Comment by createthis** [comment]
I'm sorry... what?

Here, I've created a minimal test suite for you to reproduce the issue: https://github.com/createthis/test_mocha_parallel_tests

To reproduce, do the following:
```bash
git clone https://github.com/createthis/test_mocha_parallel_tests.git
cd test_mocha_parallel_tests
npm install
npm test -- -g other # uses mocha-parallel-tests and does NOT grep properly and runs entire suite.
npm run mochatest -- -g other # uses regular mocha and DOES grep properly, running only other test
```

HTH

**Comment by 1999** [comment]
Thanks for preparing a test case! I appreciate that.
I turns that I forgot to support the alias for this option.
#205

**Comment by createthis** [comment]
Confirmed working.

I do notice that this feature seems fairly inefficient with 1100+ tests spread out amongst 93 files.

I get a lot of one line outputs and it takes much longer than a regular mocha run.

I assume this is because it is loading mocha in a separate process for each *file*, then grepping, and finally returning and compiling all of the results into the output.

An optimization might be to pre-grep the files and only spawn processes for files that appear to have matches.

A different issue though, obviously.

**Comment by 1999** [comment]
Sounds reasonable. I will create a separate issue for that.
