### ISSUE TITLE
Javascript Heap Out Of Memory Error

### ISSUE THREAD

**Issue by chen-daniel** [mocha-parallel/mocha-parallel-tests#210]
I've been running into this error on builds for awhile now. Have tried lowering max-parallel (still having this issue at 2). The entire test suite runs all the way through. Sometimes this pops up before it lists slow tests, sometimes this pops up after it lists slow tests, and sometimes before it lists errors. There are approximately 300 test files with around 4000 tests overall. 
This is the command being run
`./node_modules/mocha-parallel-tests/dist/bin/cli.js --retries 3 --max-parallel 4 --no-timeout --reporter mocha-multi --slow 10000 --require setupFile testFiles/`
I have a bit of a hacky way of getting around an issue where our tests would freeze because of workers/clients not being closed in which i added an after hook to each file which would setTimeout to allow the process to emit its end test/suite messages, and then runs process.exit(0). Removing the setTimeout does not seem to help (Just results in all the tests being pushed farther and farther to the 
 right).
May have found a possible cause in our coverage reporting.
`./node_modules/.bin/nyc --reporter=cobertura --report-dir=./test/coverage -x excludeFiles` comes before the mocha-parallel-tests command before

Any help or suggestions you can provide would help a lot!
> 20:17:11 <--- Last few GCs --->
20:17:11 
20:17:11 [55:0x55dcdc18c000]  1658174 ms: Mark-sweep 1401.1 (1462.5) -> 1394.4 (1455.8) MB, 1283.8 / 0.0 ms  allocation failure GC in old space requested
20:17:11 [55:0x55dcdc18c000]  1659591 ms: Mark-sweep 1394.4 (1455.8) -> 1394.4 (1424.8) MB, 1417.0 / 0.0 ms  last resort GC in old space requested
20:17:11 [55:0x55dcdc18c000]  1660982 ms: Mark-sweep 1394.4 (1424.8) -> 1394.4 (1424.8) MB, 1391.1 / 0.0 ms  last resort GC in old space requested
20:17:11 
20:17:11 
20:17:11 <--- JS stacktrace --->
20:17:11 
20:17:11 ==== JS stack trace =========================================
20:17:11 
20:17:11 Security context: 0x308464a25879 <JSObject>
20:17:11     1: stringSlice(aka stringSlice) [buffer.js:567] [bytecode=0x19ef7dd6a9 offset=188](this=0x1fb2089022d1 <undefined>,buf=0x38e017d953d1 <Uint8Array map = 0x306974f42839>,encoding=0x308464a34d99 <String[5]: utf-8>,start=0,end=6915609)
20:17:11     2: toString [buffer.js:633] [bytecode=0x19ef7dd2f9 offset=145](this=0x38e017d953d1 <Uint8Array map = 0x306974f42839>,encoding=0x308464a34d99 <String[5]: utf-8...
20:17:11 
20:17:11 >> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
20:17:11 >> Segmentation fault
20:17:11 >> Exited with code: 139.

**Comment by 1999** [comment]
> Just results in all the tests being pushed farther and farther to the right

This sounds pretty familiar to me. What versions of `mocha` and `mocha-parallel-tests` are you using?

> and then runs process.exit(0)

Seems like you just need to run your tests with `--exit` option.

**Comment by chen-daniel** [comment]
I've found that Instanbul has improved the way it generates the reports since the version we currently use, will close this for now. Thank you for your help!
