### ISSUE TITLE
Support mocha@6

### ISSUE THREAD

**Issue by alexkvak** [mocha-parallel/mocha-parallel-tests#217]
Have you plans to support mocha v6?

**Comment by 1999** [comment]
There shouldn't be any problems with that. Maybe you can consider sending a PR for this?
Please don't forget that mocha-parallel-tests is being tested with all mocha versions: https://github.com/mocha-parallel/mocha-parallel-tests/blob/master/package.json#L54

**Comment by alexkvak** [comment]
But there are at least two problems:

- `getOptions` is deprecated
- Statistics was refactor https://github.com/mochajs/mocha/pull/3458 so there is no `Base.stats` object anymore.

It is possible to support old version (<6) after these changes?

**Comment by 1999** [comment]
Let's start with the PR :) IIRC mocha-parallel-tests doesn't rely on these APIs so I think it should be fine.

**Comment by alexkvak** [comment]
ok, I've created #218 

> IIRC mocha-parallel-tests doesn't rely on these APIs so I think it should be fine.
of course it rely. During test run I become a lot of errors such `TypeError: Cannot read property 'passes' of undefined at Spec.Base.epilogue` and `DeprecationWarning: getOptions() is DEPRECATED and will be removed from a future version of Mocha. Use loadOptions() instead Unhandled asynchronous exception`

**Comment by 1999** [comment]
That's still good to know. Can we fix these issues first?

> DeprecationWarning: getOptions() is DEPRECATED and will be removed from a future version of Mocha. Use loadOptions() instead

As for this error:

> TypeError: Cannot read property 'passes' of undefined at Spec.Base.epilogue

Seems like `mocha` changed the way passes/fails are stored inside the runner or maybe runner is no more a thing. Would you like to investigate this or I can take a look at it in about a week or so?

**Comment by 1999** [comment]
We're almost there. Mocha@6 support is in the master branch.
I'll finish a couple of clean up tasks and publish a new version of `mocha-parallel-tests` tomorrow.

**Comment by alexkvak** [comment]
Awesome news!

**Comment by 1999** [comment]
Okies, `mocha-parallel-tests@2.1.0` has just been published. Enjoy!
