### ISSUE TITLE
How do I separate the reports for each parallel test?

### ISSUE THREAD

**Issue by franz-see** [mocha-parallel/mocha-parallel-tests#236]
Hi,

I want to have my tests run in parallel, and also have their reports created separately. 

How do I do that?

Thanks,
Franz

**Comment by 1999** [comment]
Hi @franz-see can you specify your question a little more? Right now the report for your tests when you run them with "mocha-parallel-tests" is almost the same as when you run them with "mocha". Are you missing any grouping?
