### ISSUE TITLE
Mocha-parallel-tests send wrong suite object in reporter

### ISSUE THREAD

**Issue by watson28** [mocha-parallel/mocha-parallel-tests#237]
when there are two test files **with the same description in `describe() blocks`** the library send the wrong object in report hooks.

I have a scenario where I need to get the file path from a custom reporter
```javascript
function MyReporter(runner) {
  mocha.reporters.Base.call(this, runner);

  runner.on("suite", suite => {
    if (suite.file) {
      console.log(suite.file);
    }
  });
```

And two test files, both with the same describe block
```javascript
// first.spec.js
describe("Given an existing user", function() {
  it("should contain first name", function() {});
});


// second.spec.js
describe("Given an existing user", function() {
  it("should contain last name", function() {});
});
```

When tests are executed, MyReporter logs twice `first.spec.js` instead of `first.spec.js` and `second.spec.js`

Result: MyReport logs `first.spec.js` and `first.spec.js`
Expected Result: MyReport logs `first.spec.js` and `second.spec.js`

You can see the example in real by going to https://codesandbox.io/s/mochaparalleltestsbadreporterdata-2e8cz

**Comment by watson28** [comment]
I have created a PR with a possible solution https://github.com/mocha-parallel/mocha-parallel-tests/pull/238

Let me know your thoughts.

**Comment by 1999** [comment]
@watson28 thanks for reporting this and raising a PR. It looks to me like this is a regression from #211 but I need to look a bit more into this.
