### ISSUE TITLE
TypeError: tty.getWindowSize is not a function

### ISSUE THREAD

**Issue by AntaninaKaltsova** [mocha-parallel/mocha-parallel-tests#247]
Hi! I started to get the following error:
`(node:53208) UnhandledPromiseRejectionWarning: TypeError: tty.getWindowSize is not a function
    at Object.<anonymous>` at the line `tty.getWindowSize()[1];` in *\node_modules\mocha\lib\reporters\base.js line

Сan еhis be related to the new version 2.2.0?
**Node version: v12.4.0**

**My mocha-runner.ts**

`require("dotenv").config();

import fs from "fs";
import Mocha from 'mocha-parallel-tests';
import path from "path";

const mocha = new Mocha({
    reporter: "mocha-multi-reporters",
    reporterOptions: {
        configFile: "./mocha-multi-reporters.config.json",
    },
    timeout: 120000,
    ui: "bdd",
});

const testDir = "./build/tests";

/**
 * Gets the test .js file paths recursively from a given directory.
 * @param {String} dir - path to directory containing test files.
 * @returns {Array} Filepaths to each test .js file.
 */
function getTestPaths(dir, fileList) {
    const files = fs.readdirSync(dir);
    fileList = fileList || [];

    files.forEach(function (file) {
        if (fs.statSync(path.join(dir, file)).isDirectory()) {
            fileList = getTestPaths(path.join(dir, file), fileList);
        } else {
            fileList.push(path.join(dir, file));
        }
    });

    return fileList.filter(function (file) {
        return path.extname(file) === ".js";
    });
}

// Get all .js paths and add each file to the mocha instance.
getTestPaths(testDir).forEach(function (file) {
    mocha.addFile(path.join(file));
});

// Run the tests.
mocha.run(function (failures) {
    process.exitCode = failures ? 1 : 0; // exit with non-zero status if there were failures
});
`

**Comment by 1999** [comment]
Hey @AntaninaKaltsova, thanks for checking the new version :)
What's your operating system?

**Comment by alvaroemmanuel** [comment]
Same issue here, using macOS Mojave 10.14.5

**Comment by 1999** [comment]
@alvaroemmanuel do you also run mocha-parallel-tests programmatically (not via its CLI)?

**Comment by alvaroemmanuel** [comment]
@1999 no, I'm running it through CLI, from `npm test`, I just replaced "mocha" with "mocha-parallel-tests" in my package.json scripts.test.

**Comment by 1999** [comment]
Gotcha. I could reproduce this issue but unfortunately, it doesn't fail in the CI: https://github.com/mocha-parallel/mocha-parallel-tests/pull/250. I will try to fix this in the next few days.

**Comment by 1999** [comment]
@alvaroemmanuel @AntaninaKaltsova this issue should be resolved in `mocha-parallel-tests=2.2.1`. Please re-open this issue if you still see the error.

**Comment by alvaroemmanuel** [comment]
It's working now, thanks @1999
