### ISSUE TITLE
mocha-parallel and yargs

### ISSUE THREAD

**Issue by DJ-Glock** [mocha-parallel/mocha-parallel-tests#259]
Hello.
I use mocha and puppeteer in normal and headless mode. Normally I use the following command to run tests in normal mode:
`mocha --timeout 60000 -r ts-node/register/transpile-only src/Tests/*.e2e.[jt]s --slowMo 100
`
and in headless mode:
`mocha --reporter mocha-teamcity-reporter --timeout 60000 -r ts-node/register/transpile-only src/Tests/*.e2e.[jt]s --headless --slowMo 100`

[yargs ](https://www.npmjs.com/package/yargs) is used to pass arguments from command line.
The following code is run before mocha runs each test file:

```
const opts = {
  dumpio: isDockerTest || false,
  headless: argv.headless || false,
  slowMo: argv.slowMo || 0,
  timeout: 0,
  defaultViewport: null,
  args: [
    '--start-maximized',
    '--window-size=1920,1080',
    isDockerTest && '--no-sandbox',
    isDockerTest && '--disable-setuid-sandbox',
    isDockerTest && '--disable-dev-shm-usage',
    '--enable-logging',
  ].filter(Boolean),
};

before(async () => {
  // some code
  global.browser = await launch(opts);
  const [first] = await browser.pages();
  const page = first || (await browser.newPage());
  // @ts-ignore
  global.page = page;
  // some code
});
```

But it seems that it does not work fine with mocha-parallel-tests.
If I run the following command, it will not pass args and several browsers will be launched.
`mocha-parallel-tests --reporter mocha-teamcity-reporter --timeout 60000 -r ts-node/register/transpile-only src/Tests/*.e2e.[jt]s --headless --slowMo 100`

Can you please advise how to fix this?

**Comment by 1999** [comment]
That's because mocha-parallel-tests suites run independently of each other and don't share the "global" namespace. Currently, there's no way to share any data between the threads.

**Comment by DJ-Glock** [comment]
@1999 thanks Dmitry.
