### ISSUE TITLE
sorting files option 

### ISSUE THREAD

**Issue by eladbenami** [mocha-parallel/mocha-parallel-tests#260]
hi
we want to sort the files by name (or even by file.updated descending), so we can run some files earlier than the rest.
is it possible?
from what we saw, you can just add: filesList.sort(); src/bin/options/rest.ts

thanks
Elad

**Comment by 1999** [comment]
Is there an option for this in `mocha`?

**Comment by eladbenami** [comment]
sort option in mocha - im not aware.
but the reference i wrote above is not pointing to the exact code that we need to be changed?
"filesList.sort(); src/bin/options/rest.ts"

**Comment by 1999** [comment]
I see. The idea behind `mocha-parallel-tests` is to have as less custom options as possible so that developers can switch from `mocha` to `mocha-parallel-tests` easily. If there's no such option in `mocha` than it's highly likely that we will not add it to `mocha-parallel-tests`.
