### ISSUE TITLE
tslib is required but missing from dependencies

### ISSUE THREAD

**Issue by countergram** [mocha-parallel/mocha-parallel-tests#262]
`tslib` is required in multiple places in the distributed version of this library, including the CLI, so it should be a dependency. Currently it's not a dependency but `mocha-parallel-tests` can't be run without it.

**Comment by 1999** [comment]
Thanks for reporting this. Could you provide an example which file complains of missing tslib?

**Comment by 1999** [comment]
Thanks again @countergram, version 2.2.2 should contain the fix.
