### ISSUE TITLE
Run one file many times

### ISSUE THREAD

**Issue by DJ-Glock** [mocha-parallel/mocha-parallel-tests#269]
Hello
I am looking for a simple way to run some kind of load e2e tests using mocha-parallel-tests and puppeteer. Is there any possibility to run one test file many times in parallel? As for now I can see the only one option - to make many copies of one file and run them in parallel. But it sounds stupid :)
Checked issues, possible parameters, but did not found anything.

**Comment by 1999** [comment]
What about wrapping your file contents into a for loop?

**Comment by DJ-Glock** [comment]
@1999 would you be so kind to provide some example? Because I do not understand how it will help.
As per my understanding at the moment all files and flat suites are run in parallel. Should I generate test suites by a for loop?

**Comment by 1999** [comment]
Ah, I guess I missed that point. Yes, probably generating the same files would be the best option. As for the test logic, you can probably put it into the file that you import from your tests.

**Comment by DJ-Glock** [comment]
Thanks!
