### ISSUE TITLE
Empty coverage with nyc using mocha-parallel-tests 2.2.2 but working with 2.1.0

### ISSUE THREAD

**Issue by jontxo** [mocha-parallel/mocha-parallel-tests#271]
Hello

When I try to obtain the coverage of the tests with the version 2.2.2 of mocha-parallel-tests and nyc I get 0% cover for everything but the branch in one of the files, but I use the version 2.1.0 I get the correct coverage. 
To get the coverage I use the following scripts:
`    "test": "NODE_ENV=test mocha-parallel-tests -r ts-node/register --recursive test/**/*-spec.*  --timeout 50000 --slow 1000 ",
    "test-cover": "nyc --clean npm run test",`

I have created the following repository: [feature-collector](https://github.com/jontxo/feature-collector)
where this behavior can be reproduced.

Regards

**Comment by rarms-aais** [comment]
We are experiencing this also. with any 2.2.x of mocha-parallel-test and nyc v15.0.0

**Comment by jontxo** [comment]
Now It is working with the latest versions of nyc and mocha-parallel-tests. I have updated the repository. I am going to close this issue.
