### ISSUE TITLE
New lines being spit out to stdout/stderr when a worker exits

### ISSUE THREAD

**Issue by kbkk** [mocha-parallel/mocha-parallel-tests#281]
https://github.com/mocha-parallel/mocha-parallel-tests/blob/ecc19625d1b47294debcde5d7b0870d9ddef8fb1/src/subprocess/options/exit.ts#L13

I am not sure why is this behavior needed.
`// that's what mocha does` does not mean this lib has to do it as well.
It creates a huge mess, for example I have a test suite of 30 files and when using `--grep` to filter tests I get a whole screen of new lines.

![image](https://user-images.githubusercontent.com/6276426/74914589-fd7fe680-53c2-11ea-8ac9-6597aac6071b.png)

My proposal is to remove this behavior.

**Comment by 1999** [comment]
When you run grep with `mocha` do you see these empty lines as well?

**Comment by kbkk** [comment]
Nope
